- name: Building recovery (AOSP)
  if: ${{ steps.buildtree.outputs.value == 'aosp' }}
  run: |
    source build/envsetup.sh
    export ALLOW_MISSING_DEPENDENCIES=false
    lunch twrp_${{ inputs.DEVICE_NAME }}-eng
    mkdir -p "${GITHUB_WORKSPACE}/.ccache"
    export CCACHE_DIR="${GITHUB_WORKSPACE}/.ccache"
    if [ "${{ inputs.RECOVERY_INSTALLER }}" = "true" ] && [ "${{ steps.recoveryinstaller.outputs.available }}" = "true" ]; then
      export USE_RECOVERY_INSTALLER=true
      export RECOVERY_INSTALLER_PATH=bootable/recovery/installer
    fi
    make $(tr -d _ <<< ${{ inputs.BUILD_TARGET }})image -j$(nproc --all)
  working-directory: workspace

- name: Building recovery (Omni)
  if: ${{ steps.buildtree.outputs.value == 'omni' }}
  run: |
    source build/envsetup.sh
    export ALLOW_MISSING_DEPENDENCIES=true
    lunch omni_${{ inputs.DEVICE_NAME }}-eng
    mkdir -p "${GITHUB_WORKSPACE}/.ccache"
    export CCACHE_DIR="${GITHUB_WORKSPACE}/.ccache"
    if [ "${{ inputs.RECOVERY_INSTALLER }}" = "true" ] && [ "${{ steps.recoveryinstaller.outputs.available }}" = "true" ]; then
      export USE_RECOVERY_INSTALLER=true
      export RECOVERY_INSTALLER_PATH=bootable/recovery/installer
    fi
    make ${{ inputs.BUILD_TARGET }}image -j$(nproc --all)
  working-directory: workspace
